version: "3.8"

services:
  backend:
    image: royav1/amazon-tracker-backend:latest
    container_name: django-backend
    ports:
      - "8000:8000"

  frontend:
    image: royav1/amazon-tracker-frontend:latest
    container_name: angular-frontend
    ports:
      - "4200:80"
